begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions, pg_temp;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values
 ('10000000-0000-0000-0000-000000000001','profile-a@hulog.test','{"full_name":"Google A","avatar_url":"https://example.invalid/a.png"}'),
 ('10000000-0000-0000-0000-000000000002','profile-b@hulog.test','{"full_name":"Google B"}');
create temporary table fixture(key text primary key,val text);
grant all on fixture to authenticated;
create function pg_temp.actor(n integer) returns void language sql as $$
 select set_config('request.jwt.claim.sub','10000000-0000-0000-0000-'||lpad(n::text,12,'0'),true)::text;
$$;
set local role authenticated;
select pg_temp.actor(1);
select create_group('Our profile test','Bank');
insert into fixture values ('invite',create_invite());
select pg_temp.actor(2);
select claim_invite((select val from fixture where key='invite'));
select pg_temp.actor(1);
select review_member('10000000-0000-0000-0000-000000000002',true);
select is((select avatar_kind from profiles where id=auth.uid()),'initial','Default avatar uses initial');
select is((select color from profiles where id=auth.uid()),'auto','Default color is auto');
select lives_ok($$select update_profile('  Piggy  ','emoji','🐷','green')$$,'Own profile saves');
select is((select nickname from profiles where id=auth.uid()),'Piggy','Nickname is trimmed');
select is((select avatar_emoji from profiles where id=auth.uid()),'🐷','Curated emoji saves');
select is((select color from profiles where id=auth.uid()),'green','Chosen color saves');
select is((select nickname from profiles where id<>auth.uid()),null::text,'Other member nickname untouched');
select is((select color from profiles where id<>auth.uid()),'auto','Other member color untouched');
select throws_ok($$update profiles set nickname='Not allowed' where id=auth.uid()$$,'42501','permission denied for table profiles','Direct profile updates stay forbidden');
select throws_ok($$select update_profile('Oops','initial',null,'red')$$,'P0001','Invalid profile color','Bad color rejected');
select throws_ok($$select update_profile('Oops','initial',null,null)$$,'P0001','Invalid profile color','Null color rejected');
select throws_ok($$select update_profile('Oops','emoji','💰','pink')$$,'P0001','Choose a supported emoji','Uncurated emoji rejected');
select throws_ok($$select update_profile('Oops','emoji',null,'pink')$$,'P0001','Choose a supported emoji','Emoji avatar requires emoji');
select throws_ok($$select update_profile(repeat('a',25),'initial',null,'pink')$$,'P0001','Nickname must be 1 to 24 characters','Long nickname rejected');
select throws_ok($$select update_profile('Oops','other',null,'pink')$$,'P0001','Invalid avatar kind','Invalid kind rejected');
select throws_ok($$select update_profile('Oops',null,null,'pink')$$,'P0001','Invalid avatar kind','Null kind rejected');
select is((select nickname from profiles where id=auth.uid()),'Piggy','Rejected changes are atomic');
select lives_ok($$select update_profile('  ','photo',null,'purple')$$,'Google photo can be selected');
select is((select nickname from profiles where id=auth.uid()),null::text,'Empty nickname resets to Google name');
select update_profile(repeat('a',24),'emoji','🌙','orange');
select is((select char_length(nickname) from profiles where id=auth.uid()),24,'24 character nickname accepted');
reset role;
update auth.users set raw_user_meta_data='{"full_name":"New Google A","avatar_url":"https://example.invalid/new.png"}' where id='10000000-0000-0000-0000-000000000001';
set local role authenticated;
select is((select display_name from profiles where id=auth.uid()),'New Google A','Google name still syncs');
select is((select avatar_url from profiles where id=auth.uid()),'https://example.invalid/new.png','Google photo still syncs');
select is((select nickname from profiles where id=auth.uid()),repeat('a',24),'Google sync preserves nickname');
select is((select avatar_kind from profiles where id=auth.uid()),'emoji','Google sync preserves avatar kind');
select is((select avatar_emoji from profiles where id=auth.uid()),'🌙','Google sync preserves emoji');
select is((select color from profiles where id=auth.uid()),'orange','Google sync preserves color');
select pg_temp.actor(2);
select throws_ok($$select update_profile(null,'photo',null,'blue')$$,'P0001','Google photo required','Photo requires a Google avatar');
select lives_ok($$select update_profile('Partner','initial',null,'blue')$$,'Partner can update own profile');
select is((select nickname from profiles where id<>auth.uid()),repeat('a',24),'Partner cannot change owner row');
select set_config('request.jwt.claim.sub','',true);
select throws_ok($$select update_profile(null,'initial',null,'auto')$$,'P0001','Sign in required','Missing actor rejected');
reset role;
set local role anon;
select throws_ok($$select public.update_profile(null,'initial',null,'auto')$$,'42501','permission denied for function update_profile','Anon cannot execute profile RPC');
reset role;
select ok(not has_function_privilege('anon','public.update_profile(text,text,text,text)','execute'),'Anon has no execute grant');
select ok(has_function_privilege('authenticated','public.update_profile(text,text,text,text)','execute'),'Authenticated has explicit grant');
select * from finish();
rollback;
