begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions, pg_temp;
select no_plan();
-- This clock exists only in this rolled-back test transaction.
create or replace function public.hulog_today() returns date language sql stable set search_path = public, pg_temp
as $$ select current_setting('hulog.test_date')::date $$;
select set_config('hulog.test_date','2026-11-01',true);
insert into auth.users(id,email,raw_user_meta_data) values
 ('00000000-0000-0000-0000-000000000001','a@hulog.test','{"full_name":"A"}'),
 ('00000000-0000-0000-0000-000000000002','b@hulog.test','{"full_name":"B"}'),
 ('00000000-0000-0000-0000-000000000003','c@hulog.test','{"full_name":"C"}'),
 ('00000000-0000-0000-0000-000000000004','d@hulog.test','{"full_name":"D"}'),
 ('00000000-0000-0000-0000-000000000005','e@hulog.test','{"full_name":"E"}');
create temporary table fixture(key text primary key,val text);
grant all on fixture to authenticated;
create function pg_temp.actor(n integer) returns void language sql as $$ select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-'||lpad(n::text,12,'0'),true)::text; $$;
create function pg_temp.id(k text) returns uuid language sql as $$ select val::uuid from fixture where key=k $$;
create function pg_temp.token(k text) returns text language sql as $$ select val from fixture where key=k $$;
set local role authenticated;
select pg_temp.actor(1);
insert into fixture values('group',create_group('A + B','MariBank')::text);
select is((select status from memberships where user_id=auth.uid()),'active','Owner starts active');
select throws_ok($$select create_group('Duplicate')$$,'P0001','Already has a membership','One group per user');
insert into fixture values('invite',create_invite());
select is(length(pg_temp.token('invite')),43,'Invite has 32 base64url random bytes');
select is((select token_hash from invites),encode(extensions.digest(pg_temp.token('invite'),'sha256'),'hex'),'Only invite hash stored');
select is((select expires_at-created_at from invites),interval '24 hours','Invite lasts 24 hours');
select pg_temp.actor(2);
select lives_ok($$select claim_invite(pg_temp.token('invite'))$$,'B claims invite');
select is((select status from memberships where user_id=auth.uid()),'pending','Claim is pending');
select is((select count(*) from groups),0::bigint,'Pending cannot read group');
select is((select count(*) from profiles),0::bigint,'Pending cannot read profiles');
select is((select count(*) from history),0::bigint,'Pending cannot read history');
select throws_ok($$select propose_cycle(5000,15,'2026-11-01')$$,'P0001','Active membership required','Pending cannot write group');
select pg_temp.actor(3);
select throws_ok($$select claim_invite(pg_temp.token('invite'))$$,'P0001','Invite invalid or used','Invite reuse fails');
select pg_temp.actor(1);
select is((select count(*) from profiles),2::bigint,'Owner sees requester profile and email');
select lives_ok($$select review_member('00000000-0000-0000-0000-000000000002',true)$$,'Owner accepts B');
insert into fixture values('third',create_invite());
select pg_temp.actor(3);
select claim_invite(pg_temp.token('third'));
select pg_temp.actor(1);
select throws_ok($$select review_member('00000000-0000-0000-0000-000000000003',true)$$,'P0001','Two active members maximum','Third member cannot be accepted');
select review_member('00000000-0000-0000-0000-000000000003',false);
select pg_temp.actor(3);
select is((select status from memberships where user_id=auth.uid()),'denied','Denied sees own status');
select is((select count(*) from groups),0::bigint,'Denied cannot read group');
select is((select count(*) from cycles),0::bigint,'Denied cannot read cycles');
select throws_ok($$select create_group('Elsewhere')$$,'P0001','Already has a membership','Denied membership blocks another group');
select pg_temp.actor(1);
insert into fixture values('expired',create_invite());
reset role;
update invites set expires_at=now()-interval '1 second' where token_hash=encode(extensions.digest(pg_temp.token('expired'),'sha256'),'hex');
set local role authenticated;
select pg_temp.actor(4);
select throws_ok($$select claim_invite(pg_temp.token('expired'))$$,'P0001','Invite invalid or used','Expired invite fails');
select pg_temp.actor(1);
insert into fixture values('revoked',create_invite());
select revoke_invite((select id from invites where token_hash=encode(extensions.digest(pg_temp.token('revoked'),'sha256'),'hex')));
select pg_temp.actor(4);
select throws_ok($$select claim_invite(pg_temp.token('revoked'))$$,'P0001','Invite invalid or used','Revoked invite fails');
select pg_temp.actor(1);
insert into fixture values('old',create_invite()),('new',create_invite());
select pg_temp.actor(4);
select throws_ok($$select claim_invite(pg_temp.token('old'))$$,'P0001','Invite invalid or used','New invite revokes prior unused invite');
insert into fixture values('othergroup',create_group('Other pair')::text);
select pg_temp.actor(1);
insert into fixture values('c1',propose_cycle(5000,15,'2026-11-01','00000000-0000-0000-0000-000000000002')::text);
select throws_ok($$select propose_cycle(5000,15,'2026-11-01')$$,'P0001','A live cycle already exists','Second live proposal rejected');
select throws_ok($$select respond_cycle(pg_temp.id('c1'),'accept')$$,'P0001','Other member must respond','Proposer cannot accept');
select pg_temp.actor(4);
select throws_ok($$select respond_cycle(pg_temp.id('c1'),'accept')$$,'P0001','Cycle not in your group','Nonmember cannot respond by foreign cycle ID');
select throws_ok($$select revoke_invite((select val::uuid from fixture where key='group'))$$,'P0001','Invite not owned by you','Nonmember invite ID rejected');
select pg_temp.actor(2);
select lives_ok($$select respond_cycle(pg_temp.id('c1'),'accept')$$,'B accepts cycle 1');
select throws_ok($$select update_group('Oops','Elsewhere')$$,'P0001','Owner only','Member cannot edit group');
select is((select end_date from cycles where id=pg_temp.id('c1')),'2026-11-15'::date,'Cycle 1 stored end date');
select is((select phase from cycle_summary where id=pg_temp.id('c1')),'open','Cycle 1 open');
select pg_temp.actor(1);
insert into fixture values('a1',record_payment(pg_temp.id('c1'),15)::text);
select is((select status from payments where id=pg_temp.id('a1')),'pending','Owner payment starts pending');
select ok(not (select was_confirmed from payments where id=pg_temp.id('a1')),'New owner payment was never confirmed');
select is((select pot_centavos from cycle_summary where id=pg_temp.id('c1')),0::bigint,'Pending owner payment excluded from pot');
select throws_ok($$select confirm_payment(pg_temp.id('a1'))$$,'P0001','Other member must confirm','Owner cannot confirm own payment');
select pg_temp.actor(2);
select lives_ok($$select confirm_payment(pg_temp.id('a1'))$$,'Partner confirms owner payment');
select is((select confirmed_by from payments where id=pg_temp.id('a1')),auth.uid(),'Owner payment confirmation records partner identity');
select pg_temp.actor(1);
select throws_ok($$select record_payment(pg_temp.id('c1'),1)$$,'P0001','Payment days exceed cap or are invalid','Days cap enforced');
-- B pays and A confirms separately on each of Nov 1..13.
do $$ declare pid uuid; begin for d in 1..13 loop
 perform set_config('hulog.test_date',('2026-11-01'::date+d-1)::text,true);
 perform pg_temp.actor(2); pid:=record_payment(pg_temp.id('c1'),1);
 perform pg_temp.actor(1); perform confirm_payment(pid);
end loop; end $$;
select is((select confirmed_days from member_progress where cycle_id=pg_temp.id('c1') and member_id='00000000-0000-0000-0000-000000000002'),13,'B has 13 confirmed days');
select set_config('hulog.test_date','2026-11-15',true);
select pg_temp.actor(2);
insert into fixture values('p14',record_payment(pg_temp.id('c1'),1)::text),('p15',record_payment(pg_temp.id('c1'),1)::text);
select is((select pending_count from member_progress where cycle_id=pg_temp.id('c1') and member_id=auth.uid()),2,'Two pending entries on end date');
select throws_ok($$select record_payment(pg_temp.id('c1'),1)$$,'P0001','Payment days exceed cap or are invalid','Pending days count toward cap');
select throws_ok($$select edit_payment(pg_temp.id('p14'),2)$$,'P0001','Payment days exceed cap or are invalid','Edit days cap excludes edited row but counts others');
select set_config('hulog.test_date','2026-11-16',true);
select throws_ok($$select record_payment(pg_temp.id('c1'),1)$$,'P0001','Payment window closed','Cannot pay on settling day');
select is((select phase from cycle_summary where id=pg_temp.id('c1')),'settling','Settling phase');
select pg_temp.actor(1);
select lives_ok($$select confirm_payment(pg_temp.id('p14'))$$,'P14 allowed on settling day');
select is((select pot_centavos from cycle_summary where id=pg_temp.id('c1')),145000::bigint,'Cycle 1 pot is 1450 pesos');
select is((select payout_state from cycle_summary where id=pg_temp.id('c1')),'Waiting for Got it','B payout waits');
select is((select sum(debt_centavos) from member_progress where cycle_id=pg_temp.id('c1')),0::numeric,'No debt: A fully paid and B is receiver');
select pg_temp.actor(2);
select lives_ok($$select receive_payout(pg_temp.id('c1'))$$,'B taps Got it');
select is((select payout_state from cycle_summary where id=pg_temp.id('c1')),'Received','Got it recorded');
insert into fixture values('c2',propose_cycle(10000,10,'2026-11-20')::text);
select is((select receiver_id from cycles where id=pg_temp.id('c2')),'00000000-0000-0000-0000-000000000001'::uuid,'Default next receiver A');
select set_config('hulog.test_date','2026-11-17',true);
select pg_temp.actor(1);
select throws_ok($$select confirm_payment(pg_temp.id('p15'))$$,'P0001','Confirmation window closed','Never-confirmed P15 blocked after settling');
select lives_ok($$select respond_cycle(pg_temp.id('c2'),'accept')$$,'A accepts cycle 2 on Nov 17');
select is((select phase from cycle_summary where id=pg_temp.id('c2')),'upcoming','Upcoming phase');
insert into fixture values('a2',record_payment(pg_temp.id('c2'),10)::text);
select pg_temp.actor(2); select confirm_payment(pg_temp.id('a2'));
select pg_temp.actor(1);
select lives_ok($$select edit_payment(pg_temp.id('a2'),9)$$,'Owner can correct ahead-of-start payment');
select is((select status from payments where id=pg_temp.id('a2')),'pending','Owner payment edit resets to pending');
select ok((select was_confirmed from payments where id=pg_temp.id('a2')),'Owner correction preserves was_confirmed');
select ok((select confirmed_by is null and confirmed_at is null from payments where id=pg_temp.id('a2')),'Owner correction clears confirmation metadata');
select edit_payment(pg_temp.id('a2'),10);
select pg_temp.actor(2); select confirm_payment(pg_temp.id('a2'));
insert into fixture values('b4',record_payment(pg_temp.id('c2'),4)::text),('b3',record_payment(pg_temp.id('c2'),3)::text);
select throws_ok($$select confirm_payment(pg_temp.id('b4'))$$,'P0001','Other member must confirm','B cannot confirm own payment');
select pg_temp.actor(1);
select confirm_payment(pg_temp.id('b4')); select confirm_payment(pg_temp.id('b3'));
select set_config('hulog.test_date','2026-11-30',true);
select is((select pot_centavos from cycle_summary where id=pg_temp.id('c2')),170000::bigint,'Cycle 2 pot is 1700 pesos');
select is((select payout_state from cycle_summary where id=pg_temp.id('c2')),'Received','Owner receiver auto Received');
select is((select debt_centavos from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),30000::bigint,'B owes 300 pesos');
select pg_temp.actor(2);
insert into fixture values('r1',record_repayment(pg_temp.id('c2'),auth.uid(),30000)::text);
select throws_ok($$select record_repayment(pg_temp.id('c2'),auth.uid(),100)$$,'P0001','Repayment exceeds cap or is invalid','Pending repayment reserves entire debt cap');
select throws_ok($$select confirm_repayment(pg_temp.id('r1'))$$,'P0001','Creditor only','Only creditor confirms');
select pg_temp.actor(1);
select confirm_repayment(pg_temp.id('r1'));
select is((select debt_centavos from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),0::bigint,'Confirmed repayment clears debt');
insert into fixture values('c3',propose_cycle(10000,10,'2026-12-01')::text);
select pg_temp.actor(2); select respond_cycle(pg_temp.id('c3'),'accept');
select is((select pot_centavos from cycle_summary where id=pg_temp.id('c3')),0::bigint,'Cycle 3 pot unaffected by repayments');
select mark_history_seen();
select set_config('hulog.test_date','2026-12-02',true);
select pg_temp.actor(1);
select edit_payment(pg_temp.id('b3'),2);
select is((select status from payments where id=pg_temp.id('b3')),'pending','Closed-cycle correction returns to pending');
select ok((select was_confirmed from payments where id=pg_temp.id('b3')),'Correction preserves was_confirmed');
select is((select confirmed_days from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),4,'B confirmed 400 after correction');
select is((select debt_centavos from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),30000::bigint,'Debt becomes 300 pending re-confirmation');
select pg_temp.actor(2);
select ok(exists(select 1 from history h join memberships m on m.group_id=h.group_id and m.user_id=auth.uid() where h.actor_id<>auth.uid() and h.created_at>m.last_seen_history_at and h.entity_id=pg_temp.id('b3')),'B sees unread correction history');
select pg_temp.actor(1);
select lives_ok($$select confirm_payment(pg_temp.id('b3'))$$,'Originally confirmed entry can be reconfirmed after close');
select is((select confirmed_days from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),6,'B confirmed 600');
select is((select debt_centavos from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),10000::bigint,'Debt becomes 100');
select is((select phase from cycle_summary where id=pg_temp.id('c1')),'ended','Ended phase');
-- Make room, then edit a never-confirmed payment: it must remain unconfirmable.
select edit_payment(pg_temp.id('a1'),14);
select edit_payment((select id from payments where cycle_id=pg_temp.id('c1') and member_id='00000000-0000-0000-0000-000000000002' and status='confirmed' limit 1),null,true);
select edit_payment(pg_temp.id('p15'),2);
select throws_ok($$select confirm_payment(pg_temp.id('p15'))$$,'P0001','Confirmation window closed','Editing originally pending payment does not bypass deadline');
select edit_repayment(pg_temp.id('r1'),20000);
select is((select status from repayments where id=pg_temp.id('r1')),'pending','Repayment correction resets to pending');
select ok((select was_confirmed from repayments where id=pg_temp.id('r1')),'Repayment keeps was_confirmed');
select confirm_repayment(pg_temp.id('r1'));
select is((select debt_centavos from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),20000::bigint,'Repayment edit recalculates debt');
select throws_ok($$select edit_repayment(pg_temp.id('r1'),50000)$$,'P0001','Repayment exceeds cap or is invalid','Repayment edit cap');
select edit_repayment(pg_temp.id('r1'),null,true);
select is((select debt_centavos from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),40000::bigint,'Deleted repayment excluded');
insert into fixture values('creditor-recorded',record_repayment(pg_temp.id('c2'),'00000000-0000-0000-0000-000000000002',40000)::text);
select confirm_repayment(pg_temp.id('creditor-recorded'));
select edit_payment(pg_temp.id('b4'),8);
select confirm_payment(pg_temp.id('b4'));
select is((select debt_centavos from member_progress where cycle_id=pg_temp.id('c2') and member_id='00000000-0000-0000-0000-000000000002'),0::bigint,'Overpaid repayment never creates reverse debt after payment correction');
select pg_temp.actor(2);
select lives_ok($$select edit_payment(pg_temp.id('a2'),9)$$,'Either active member can correct owner payment');
select is((select status from payments where id=pg_temp.id('a2')),'pending','Partner correction of owner payment resets to pending');
select pg_temp.actor(1);
select throws_ok($$select confirm_payment(pg_temp.id('a2'))$$,'P0001','Other member must confirm','Owner cannot reconfirm own corrected payment');
select pg_temp.actor(2);
select lives_ok($$select confirm_payment(pg_temp.id('a2'))$$,'Partner can reconfirm corrected owner payment after close');
select pg_temp.actor(1);
select throws_ok($$select record_repayment(pg_temp.id('c3'),'00000000-0000-0000-0000-000000000001',100)$$,'P0001','Cycle must be closed','Open cycle cannot have repayment');
-- Late acceptance, decline and cancel.
select set_config('hulog.test_date','2026-12-12',true);
insert into fixture values('late',propose_cycle(100,1,'2026-12-12')::text);
select set_config('hulog.test_date','2026-12-13',true);
select pg_temp.actor(2);
select throws_ok($$select respond_cycle(pg_temp.id('late'),'accept')$$,'P0001','Proposal start date has passed','Accept after start rejected');
select respond_cycle(pg_temp.id('late'),'decline');
select pg_temp.actor(1);
insert into fixture values('cancel',propose_cycle(100,1)::text);
select is((select start_date from cycles where id=pg_temp.id('cancel')),'2026-12-14'::date,'Default start is tomorrow');
select respond_cycle(pg_temp.id('cancel'),'cancel');
select pg_temp.actor(1);
select set_notification_prefs('19:30',true);
select set_notification_language('en');
select save_push_subscription('https://push.example.test/sub-a','p256dh-a','auth-a');
select is((select reminder_time::text||':'||enabled::text from get_notification_prefs()),'19:30:00:true','Owner can read own notification preferences through the RPC');
select is((select language from get_notification_prefs()),'en','Owner can set and read own notification language through the RPC');
select throws_ok($$select set_notification_language('fr')$$,'P0001','Valid notification language required','Invalid notification language is rejected');
select is((select count(*) from get_push_subscriptions()),1::bigint,'Owner can read own push subscription through the RPC');
select pg_temp.actor(2);
select is((select reminder_time::text||':'||enabled::text from get_notification_prefs()),'20:00:00:false','Member receives only their own default preferences');
select is((select language from get_notification_prefs()),'taglish','Member keeps their own default notification language');
select set_notification_language('tl');
select is((select language from get_notification_prefs()),'tl','Member can change only their own notification language');
select is((select count(*) from get_push_subscriptions()),0::bigint,'Member cannot read the owner subscription through the RPC');
select throws_ok($$select save_push_subscription('https://push.example.test/sub-a','p256dh-x','auth-x')$$,'P0001','Push subscription belongs to another account','Member cannot claim the owner subscription endpoint');
select delete_push_subscription('https://push.example.test/sub-a');
select throws_ok($$select * from push_subscriptions$$,'42501','permission denied for table push_subscriptions','Direct subscription reads are denied');
select throws_ok($$select * from notification_prefs$$,'42501','permission denied for table notification_prefs','Direct preference reads are denied');
select throws_ok($$select * from notification_log$$,'42501','permission denied for table notification_log','Notification log is not readable by clients');
select pg_temp.actor(4);
select throws_ok($$select record_payment(pg_temp.id('c2'),1)$$,'P0001','Cycle not in your group','Foreign payment cycle blocked');
select throws_ok($$select edit_payment(pg_temp.id('b4'),1)$$,'P0001','Payment not in your group','Foreign payment edit blocked');
select throws_ok($$select confirm_payment(pg_temp.id('b4'))$$,'P0001','Payment not in your group','Foreign payment confirm blocked');
select throws_ok($$select receive_payout(pg_temp.id('c2'))$$,'P0001','Cycle not in your group','Foreign payout blocked');
select throws_ok($$select give_payout(pg_temp.id('c2'))$$,'P0001','Cycle not in your group','Foreign payout hand-off blocked');
select throws_ok($$select record_repayment(pg_temp.id('c2'),auth.uid(),100)$$,'P0001','Cycle not in your group','Foreign repayment blocked');
select throws_ok($$select edit_repayment(pg_temp.id('r1'),100)$$,'P0001','Repayment not in your group','Foreign repayment edit blocked');
select throws_ok($$select confirm_repayment(pg_temp.id('r1'))$$,'P0001','Repayment not in your group','Foreign repayment confirm blocked');
select is((select count(*) from cycle_summary),0::bigint,'Invoker view hides foreign cycles');
select is((select count(*) from member_progress),0::bigint,'Invoker view hides foreign progress');
select throws_ok($$insert into groups(name,owner_id) values('hack',auth.uid())$$,'42501','permission denied for table groups','Direct insert forbidden');
select throws_ok($$update payments set days=1$$,'42501','permission denied for table payments','Direct update forbidden');
select throws_ok($$delete from history$$,'42501','permission denied for table history','History append-only for clients');
reset role;
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('profiles'::regclass,'groups'::regclass,'memberships'::regclass,'invites'::regclass,'cycles'::regclass,'payments'::regclass,'repayments'::regclass,'history'::regclass,'push_subscriptions'::regclass,'notification_prefs'::regclass,'notification_log'::regclass)),'RLS on every table');
select ok((select bool_and(proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace in ('public'::regnamespace,'private'::regnamespace) and prosecdef),'All definers pin search_path');
select ok(not has_function_privilege('anon','public.record_payment(uuid,integer)','execute'),'Anon has no RPC write access');
select ok(not has_function_privilege('authenticated','private.lock_cycle(uuid)','execute'),'Internal write helpers inaccessible');
select ok((select bool_and(not has_table_privilege('authenticated',t,'INSERT,UPDATE,DELETE')) from unnest(array['profiles','groups','memberships','invites','cycles','payments','repayments','history']) as t),'All table writes revoked from authenticated');
select ok((select bool_and(not has_table_privilege('anon',t,'SELECT,INSERT,UPDATE,DELETE')) from unnest(array['profiles','groups','memberships','invites','cycles','payments','repayments','history']) as t),'Anon cannot access any table');
select ok(has_table_privilege('authenticated','push_subscriptions','SELECT') is false and has_table_privilege('authenticated','notification_prefs','SELECT') is false and has_table_privilege('authenticated','notification_log','SELECT') is false,'Notification tables have no direct authenticated grants');
select ok(exists(select 1 from push_subscriptions where user_id='00000000-0000-0000-0000-000000000001' and endpoint='https://push.example.test/sub-a'),'Member cannot delete another user subscription');
select ok(not has_function_privilege('anon','public.set_notification_prefs(time,boolean)','execute'),'Anon cannot call notification preference RPC');
select ok(not has_function_privilege('anon','public.set_notification_language(text)','execute'),'Anon cannot call notification language RPC');
select ok((select bool_and(proconfig @> array['search_path=public, pg_temp']) from pg_proc where pronamespace='public'::regnamespace and prosecdef and proname in ('get_notification_prefs','set_notification_prefs','set_notification_language','get_push_subscriptions','save_push_subscription','delete_push_subscription')),'Notification RPCs pin search_path');
select * from finish();
rollback;
